version: '3.7'
services:
  grafana:
    image: grafana/grafana:7.5.16
    ports:
      - 3000:3000
    volumes:
      - ./splunk-datasource:/var/lib/grafana/plugins/splunk-datasource

  splunk:
    image: splunk/splunk:8.2.6
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=splunk/splunk
